# main menu navigation
menu:
  Home: /
  About: /about
  # Archive: /archive

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  github: hopeideal

user:
  name: 银白
  avatar: /images/avatar.png
  location: 上海
  description: 这个人很懒，什么也没写~
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: Hopeideal/cuptea.net # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png

font:
  enable: true
  # 外链字体库地址，例如 //fonts.googleapis.com (默认值)
  host: 
  # 全局字体，应用在 body 元素上
  global:
    external: true
    family: Monda
  # 标题字体 (h1, h2, h3, h4, h5, h6)
  headings:
    external: true
    family: Roboto Slab
  # 文章字体
  posts:
    external: true
    family:
  # Logo 字体
  logo:
    external: true
    family:
  # 代码字体，应用于 code 以及代码块
  codes:
    external: true
    family:
